override: false
sources:
  - includes/table/linux-kernel-version-production.rst
  - includes/fact-installation-bind-ip-default-in-config.rst
  - includes/note-minimum-glibc.rst
  - includes/introduction-query-matching.rst
  - includes/install-copy-release-linux-i686.rst
  - includes/install-copy-release-linux-i686.rst
  - includes/install-copy-release-linux-x86_64.rst
  - includes/install-copy-release-osx-x86_64.rst
  - includes/install-curl-release-ent-amzn64.rst
  - includes/install-curl-release-ent-rhel62.rst
  - includes/install-curl-release-ent-suse11.rst
  - includes/install-curl-release-ent-ubuntu1204.rst
  - includes/install-curl-release-linux-i686.rst
  - includes/install-curl-release-linux-i686.rst
  - includes/install-curl-release-linux-x86_64.rst
  - includes/install-curl-release-osx-x86_64.rst
  - includes/install-untar-release-linux-i686.rst
  - includes/install-untar-release-linux-i686.rst
  - includes/install-untar-release-linux-x86_64.rst
  - includes/install-untar-release-osx-x86_64.rst
  - includes/steps-install-mongodb-on-linux.yaml
  - includes/steps-install-mongodb-on-debian.yaml
  - includes/steps-install-mongodb-on-linux-32.yaml
  - includes/steps-install-mongodb-on-linux-64.yaml
  - includes/steps-install-mongodb-on-osx-manually.yaml
  - includes/steps-install-mongodb-on-osx-with-homebrew.yaml
  - includes/steps-install-mongodb-on-red-hat-centos-or-fedora-linux.yaml
  - includes/steps-install-mongodb-on-ubuntu.yaml
  - includes/steps-install-mongodb-on-windows.yaml
  - includes/steps-run-mongodb-on-a-linux-distribution.yaml
  - includes/steps-run-mongodb-on-debian.yaml
  - includes/steps-run-mongodb-on-linux.yaml
  - includes/steps-run-mongodb-on-windows.yaml
  - includes/toc-installation-linux.yaml
  - includes/toc-installation-osx.yaml
  - includes/toc-installation-windows.yaml
  - includes/toc-spec-installation-linux-other.yaml
  - includes/toc-spec-installation-linux-packages.yaml
  - tutorial/install-mongodb-on-debian.txt
  - tutorial/install-mongodb-on-linux.txt
  - tutorial/install-mongodb-on-os-x.txt
  - tutorial/install-mongodb-on-ubuntu.txt
  - includes/driver-table.rst
  - includes/fact-id-values-generated.rst
  - includes/steps-getting-started-prereq.yaml
  - includes/example/example-gs-insert-prereq.yaml
  - includes/example/example-gs-insert.yaml
  - includes/example/example-gs-insert-array.yaml
  - includes/example/example-gs-query-all.yaml
  - includes/example/example-gs-query-equality.yaml
  - includes/example/example-gs-query-operators.yaml
  - includes/example/example-gs-query-combination.yaml
  - includes/example/example-gs-query-sort.yaml
  - includes/example/example-gs-update-fields.yaml
  - includes/example/example-gs-update-replace.yaml
  - includes/example/example-gs-remove.yaml
  - includes/example/example-gs-aggregation.yaml
  - includes/example/example-gs-index.yaml
  - includes/steps-getting-started-prereq-python.yaml
  - includes/example/example-gs-insert-prereq-python.yaml
  - includes/example/example-gs-insert-python.yaml
  - includes/example/example-gs-insert-multiple-python.yaml
  - includes/example/example-gs-query-all-python.yaml
  - includes/example/example-gs-query-equality-python.yaml
  - includes/example/example-gs-query-operators-python.yaml
  - includes/example/example-gs-query-combination-python.yaml
  - includes/example/example-gs-query-sort-python.yaml
  - includes/example/example-gs-update-fields-python.yaml
  - includes/example/example-gs-update-replace-python.yaml
  - includes/example/example-gs-remove-python.yaml
  - includes/example/example-gs-aggregation-python.yaml
  - includes/example/example-gs-index-python.yaml
...
