source: build/cpp-examples/examples/mongocxx/aggregate.cpp
target: includes/example-prereq-cpp-aggregate.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/aggregate.cpp
target: includes/example-cpp-group-documents-by-a-field-and-calculate-count.cpp
truncate:
   start-after: "// @begin: cpp-group-documents-by-a-field-and-calculate-count"
   end-before: "// @end: cpp-group-documents-by-a-field-and-calculate-count"
---
source: build/cpp-examples/examples/mongocxx/aggregate.cpp
target: includes/example-cpp-filter-and-group-documents.cpp
truncate:
   start-after: "// @begin: cpp-filter-and-group-documents"
   end-before: "// @end: cpp-filter-and-group-documents"
---
source: build/cpp-examples/examples/mongocxx/create.cpp
target: includes/example-prereq-cpp-create.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/create.cpp
target: includes/example-cpp-insert-a-document.cpp
truncate:
   start-after: "// @begin: cpp-insert-a-document"
   end-before: "// @end: cpp-insert-a-document"
---
source: build/cpp-examples/examples/mongocxx/index.cpp
target: includes/example-prereq-cpp-index.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/index.cpp
target: includes/example-cpp-single-field-index.cpp
truncate:
   start-after: "// @begin: cpp-single-field-index"
   end-before: "// @end: cpp-single-field-index"
---
source: build/cpp-examples/examples/mongocxx/index.cpp
target: includes/example-cpp-create-compound-index.cpp
truncate:
   start-after: "// @begin: cpp-create-compound-index"
   end-before: "// @end: cpp-create-compound-index"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-prereq-cpp-query.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-all.cpp
truncate:
   start-after: "// @begin: cpp-query-all"
   end-before: "// @end: cpp-query-all"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-top-level-field.cpp
truncate:
   start-after: "// @begin: cpp-query-top-level-field"
   end-before: "// @end: cpp-query-top-level-field"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-embedded-document.cpp
truncate:
   start-after: "// @begin: cpp-query-embedded-document"
   end-before: "// @end: cpp-query-embedded-document"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-field-in-array.cpp
truncate:
   start-after: "// @begin: cpp-query-field-in-array"
   end-before: "// @end: cpp-query-field-in-array"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-greater-than.cpp
truncate:
   start-after: "// @begin: cpp-query-greater-than"
   end-before: "// @end: cpp-query-greater-than"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-less-than.cpp
truncate:
   start-after: "// @begin: cpp-query-less-than"
   end-before: "// @end: cpp-query-less-than"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-logical-and.cpp
truncate:
   start-after: "// @begin: cpp-query-logical-and"
   end-before: "// @end: cpp-query-logical-and"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-logical-or.cpp
truncate:
   start-after: "// @begin: cpp-query-logical-or"
   end-before: "// @end: cpp-query-logical-or"
---
source: build/cpp-examples/examples/mongocxx/query.cpp
target: includes/example-cpp-query-sort.cpp
truncate:
   start-after: "// @begin: cpp-query-sort"
   end-before: "// @end: cpp-query-sort"
---
source: build/cpp-examples/examples/mongocxx/remove.cpp
target: includes/example-prereq-cpp-remove.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/remove.cpp
target: includes/example-cpp-remove-matching-documents.cpp
truncate:
   start-after: "// @begin: cpp-remove-matching-documents"
   end-before: "// @end: cpp-remove-matching-documents"
---
source: build/cpp-examples/examples/mongocxx/remove.cpp
target: includes/example-cpp-remove-justone.cpp
truncate:
   start-after: "// @begin: cpp-remove-justone"
   end-before: "// @end: cpp-remove-justone"
---
source: build/cpp-examples/examples/mongocxx/remove.cpp
target: includes/example-cpp-remove-all-documents.cpp
truncate:
   start-after: "// @begin: cpp-remove-all-documents"
   end-before: "// @end: cpp-remove-all-documents"
---
source: build/cpp-examples/examples/mongocxx/remove.cpp
target: includes/example-cpp-drop-collection.cpp
truncate:
   start-after: "// @begin: cpp-drop-collection"
   end-before: "// @end: cpp-drop-collection"
---
source: build/cpp-examples/examples/mongocxx/update.cpp
target: includes/example-prereq-cpp-update.cpp
truncate:
   end-before: "int main(int, char**)"
---
source: build/cpp-examples/examples/mongocxx/update.cpp
target: includes/example-cpp-update-top-level-fields.cpp
truncate:
   start-after: "// @begin: cpp-update-top-level-fields"
   end-before: "// @end: cpp-update-top-level-fields"
---
source: build/cpp-examples/examples/mongocxx/update.cpp
target: includes/example-cpp-update-embedded-field.cpp
truncate:
   start-after: "// @begin: cpp-update-embedded-field"
   end-before: "// @end: cpp-update-embedded-field"
---
source: build/cpp-examples/examples/mongocxx/update.cpp
target: includes/example-cpp-update-multiple-documents.cpp
truncate:
   start-after: "// @begin: cpp-update-multiple-documents"
   end-before: "// @end: cpp-update-multiple-documents"
---
source: build/cpp-examples/examples/mongocxx/update.cpp
target: includes/example-cpp-replace-document.cpp
truncate:
   start-after: "// @begin: cpp-replace-document"
   end-before: "// @end: cpp-replace-document"
...