override: false
sources:
  - includes/introduction-write-concern.rst
  - includes/table/linux-kernel-version-production.rst
  - includes/note-minimum-glibc.rst
  - includes/introduction-query-matching.rst
  - includes/install-copy-release-linux-i686.rst
  - includes/install-copy-release-linux-i686.rst
  - includes/install-copy-release-linux-x86_64.rst
  - includes/install-copy-release-osx-x86_64.rst
  - includes/install-curl-release-ent-amzn64.rst
  - includes/install-curl-release-ent-rhel62.rst
  - includes/install-curl-release-ent-suse11.rst
  - includes/install-curl-release-ent-ubuntu1204.rst
  - includes/install-curl-release-linux-i686.rst
  - includes/install-curl-release-linux-i686.rst
  - includes/install-curl-release-linux-x86_64.rst
  - includes/install-curl-release-osx-x86_64.rst
  - includes/install-untar-release-linux-i686.rst
  - includes/install-untar-release-linux-i686.rst
  - includes/install-untar-release-linux-x86_64.rst
  - includes/install-untar-release-osx-x86_64.rst
  - includes/steps-install-mongodb-on-linux.yaml
  - includes/steps-install-mongodb-on-debian.yaml
  - includes/steps-install-mongodb-on-linux-32.yaml
  - includes/steps-install-mongodb-on-linux-64.yaml
  - includes/steps-install-mongodb-on-osx-manually.yaml
  - includes/steps-install-mongodb-on-osx-with-homebrew.yaml
  - includes/steps-install-mongodb-on-red-hat-centos-or-fedora-linux.yaml
  - includes/steps-install-mongodb-on-ubuntu.yaml
  - includes/steps-install-mongodb-on-windows.yaml
  - includes/steps-run-mongodb-on-a-linux-distribution.yaml
  - includes/steps-run-mongodb-on-debian.yaml
  - includes/steps-run-mongodb-on-linux.yaml
  - includes/steps-run-mongodb-on-windows.yaml
  - includes/steps-create-manually-windows-service-for-mongodb-enterprise.yaml
  - includes/toc-installation-linux.yaml
  - includes/toc-installation-osx.yaml
  - includes/toc-installation-windows.yaml
  - includes/toc-spec-installation-linux-other.yaml
  - includes/toc-spec-installation-linux-packages.yaml
  - tutorial/install-mongodb-on-debian.txt
  - tutorial/install-mongodb-on-linux.txt
  - tutorial/install-mongodb-on-os-x.txt
  - tutorial/install-mongodb-on-ubuntu.txt
  - includes/steps-getting-started-insert-prereq.yaml
  - includes/steps-getting-started-insert.yaml
  - includes/steps-getting-started-insert-an-array.yaml
  - includes/steps-getting-started-insert-bulk.yaml
  - includes/steps-getting-started-query-prereq.yaml
  - includes/steps-getting-started-query-all.yaml
  - includes/steps-getting-started-query-equality.yaml
  - includes/steps-getting-started-query-operators.yaml
  - includes/steps-getting-started-query-projection.yaml
  - includes/steps-getting-started-update.yaml
  - includes/steps-getting-started-update-replace.yaml
  - includes/steps-getting-started-update-multiple-fields.yaml
  - includes/steps-getting-started-update-upsert.yaml
  - includes/steps-getting-started-remove.yaml
  - includes/steps-getting-started-drop.yaml
  - includes/steps-getting-started-aggregation-prereq.yaml
  - includes/steps-getting-started-aggregation.yaml
  - includes/steps-getting-started-index.yaml
  - includes/steps-getting-started-index-compound.yaml
  - includes/steps-getting-started-index-unique.yaml
  - includes/steps-getting-started-index-list.yaml
  - includes/steps-getting-started-index-remove.yaml
  - includes/steps-getting-started-index-modify.yaml
  - includes/steps-getting-started-index-explain.yaml
  - includes/steps-getting-started-index-hint.yaml
  - includes/driver-table.rst
  - includes/fact-id-values-generated.rst
  - includes/example/example-gs-query-all.yaml
  - includes/example/example-gs-query-equality.yaml
  - includes/example/example-gs-query-operators.yaml
  - includes/example/example-gs-query-sort.yaml
  - includes/example/example-gs-aggregation.yaml
  - includes/example/example-gs-remove.yaml
  - includes/example/example-gs-update-fields.yaml
  - includes/example/example-gs-update-replace.yaml
  - includes/example/example-gs-index.yaml
  - includes/example/example-gs-insert-prereq.yaml
  - includes/example/example-gs-insert.yaml
  - includes/example/example-gs-insert-array.yaml
---
source: administration/install-enterprise.txt
target: tutorial/install-enterprise.rst
...
