# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.

editions:
  - 'shell'
  - 'python'
  - 'java'
### --- ####
java-web-base:
  edition: java
  inherit: java-base
  tags:
    - java
    - hosted
    - web
    - website
java-print-base:
  edition: java
  inherit: java-base
  tags:
    - hosted
    - java
    - print

python-web-base:
  edition: python
  inherit: python-base
  tags:
    - python
    - web
    - website
python-print-base:
  edition: python
  inherit: python-base
  tags:
    - python
    - print
shell-web-base:
  edition: shell
  inherit: shell-base
  tags:
    - shell
    - web
    - website
shell-print-base:
  edition: shell
  inherit: shell-base
  tags:
    - shell
    - print
### --- ####
dirhtml-python:
  builder: dirhtml
  inherit: python-web-base
html-python:
  builder: html
  inherit: python-web-base
gettext-python:
  builder: gettext
  inherit: python-web-base
singlehtml-python:
  builder: singlehtml
  inherit: python-web-base
epub-python:
  builder: epub
  inherit: python-print-base
latex-python:
  builder: latex
  inherit: python-print-base
json-python:
  builder: json
  inherit: python-web-base

dirhtml-java:
  builder: dirhtml
  inherit: java-web-base
html-java:
  builder: html
  inherit: java-web-base
gettext-java:
  builder: gettext
  inherit: java-web-base
singlehtml-java:
  builder: singlehtml
  inherit: java-web-base
epub-java:
  builder: epub
  inherit: java-print-base
json-java:
  builder: json
  inherit: java-web-base
latex-java:
  builder: latex
  inherit: java-print-base

dirhtml-shell:
  builder: dirhtml
  inherit: shell-web-base
html-shell:
  builder: html
  inherit: shell-web-base
gettext-shell:
  builder: gettext
  inherit: shell-web-base
singlehtml-shell:
  builder: singlehtml
  inherit: shell-web-base
epub-shell:
  builder: epub
  inherit: shell-print-base
json-shell:
  builder: json
  inherit: shell-web-base
latex-shell:
  builder: latex
  inherit: shell-print-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
  tags: ['primer', 'getting-started']
java-base:
  inherit: root-base
  edition: java
  excluded: []
python-base:
  inherit: root-base
  edition: python
  excluded: []
shell-base:
  inherit: root-base
  edition: shell
  excluded: []
...
