pre:
  - command: git.get_project
    params:
      directory: "docs-mongodb"
  - command: git.apply_patch
    params:
      directory: "docs-mongodb"
  - command: shell.exec
    params:
      working_dir: "docs-mongodb"
      script: |
        virtualenv ~/venv

        ${venv}/pip install -r requirements.txt


tasks:
  - name: "build_manual"
    commands:
    - command: shell.exec
      params:
        working_dir: "docs-mongodb"
        script: |
          ${venv}/giza generate source
          ${venv}/giza sphinx --builder publish --serial_sphinx
    - command: shell.exec
      params:
        working_dir: "docs-mongodb"
        script: |
          ${venv}/giza env package --builder publish
          ${venv}/giza packaging create --target push

  # TODO: deploy build/archive/* to s3

buildvariants:
  - name: ubuntu1404-release
    display_name: "Ubuntu 14.04"
    run_on:
      - ubuntu1404-test
    expansions:
      venv: "~/venv/bin"
    tasks:
      - name: "build_manual"
