file: /tutorial/adjust-replica-set-member-priority
description: |
  Change a :term:`replica set` member's
  :data:`~local.system.replset.members[n].priority` level. Replica
  sets elect :term:`primaries <primary>` based on member priority
  levels.
---
file: /tutorial/configure-secondary-only-replica-set-member
description: |
  Make a :term:`secondary` member ineligible for election as :term:`primary`.
---
file: /tutorial/configure-a-hidden-replica-set-member
description: |
  Configure a member that contains a copy of the data set and that votes,
  but that cannot cannot become primary and cannot be accessed by
  applications.
---
file: /tutorial/configure-a-delayed-replica-set-member
description: |
  Configure a member that cotains a copy of the data set but without the
  most recent changes, in order to provide a rolling backup.
---
file: /tutorial/configure-a-non-voting-replica-set-member
description: |
  Configure a member that contains a copy of the data set and that can
  accept read operations, but that does not vote. Hidden members allow
  you to add additional members for read distribution beyond the
  maximum seven voting members.
---
file: /tutorial/convert-secondary-into-arbiter
description: |
  Convert a secondary to an :ref:`arbiter <replica-set-arbiters>` if
  the member no longer needs to hold data but needs to remain in the
  set to ensure an odd number of members for :ref:`elections
  <replica-set-elections>`.
...
