file: /tutorial/adjust-replica-set-member-priority
description: |
  Change the precedence given to a :term:`replica set` member in an
  :ref:`election <replica-set-elections>` for :term:`primary`.
---
file: /tutorial/configure-secondary-only-replica-set-member
description: |
  Make a :term:`secondary` member ineligible for election as primary.
---
file: /tutorial/configure-a-hidden-replica-set-member
description: |
  Create a secondary member that keeps a copy of the data set and that
  votes but that never becomes primary and cannot be accessed by
  applications.
---
file: /tutorial/configure-a-delayed-replica-set-member
description: |
  Create a secondary member that keeps a delayed copy of the data set in
  order to provide a rolling backup.
---
file: /tutorial/configure-a-non-voting-replica-set-member
description: |
  Create a secondary member that keeps a copy of the data set and
  accepts read operations but that does not vote. Non-voting members
  allow you to add additional members for read distribution beyond the
  maximum seven voting members.
---
file: /tutorial/convert-secondary-into-arbiter
description: |
  Convert a secondary to an :ref:`arbiter <replica-set-arbiters>` if
  the member no longer needs to hold data but needs to remain in the
  set to ensure an odd number of members for elections.
...
