file: /tutorial/deploy-replica-set
description: |
    Configure a three-member :term:`replica set` for either a
    development or production system.
---
file: /tutorial/deploy-geographically-distributed-replica-set
description: |
    Create a replica set with members located in multiple locations to
    protect against facility-specific failures, such as power outages.
---
file: /tutorial/add-replica-set-arbiter
description: |
    Add an :term:`arbiter` to break :ref:`election
    <replica-set-elections>` ties in a replica set with an even number
    of members. An arbiter does not hold database data.
---
file: /tutorial/convert-standalone-to-replica-set
description: |
    Convert an existing, standalone :program:`mongod` instance into a
    three-member replica set.
---
file: /tutorial/expand-replica-set
description: |
    Add a :program:`mongod` instance to an existing replica set.
---
file: /tutorial/remove-replica-set-member
description: |
    Remove a :program:`mongod` instance from a replica set.
---
file: /tutorial/replace-replica-set-member
description: |
    Change a replica set member's hostname in the
    :data:`local.system.replset` collection. Use this procedure when the
    hostname for the member's :program:`mongod` instance has changed'.
...
