fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  links:
    - { 'manual': 'master' }
    - { 'v2.6': 'manual' }
  targets:
    - 'latex'
    - 'html'
    - 'man'
    - 'dirhtml'
  doc-root:
    - 'sitemap.xml'
    - 'osd.xml'
    - '.htaccess'
    - '10gen-gpg-key.asc'
    - '10gen-security-gpg-key.asc'
  branch-root: null
...
