fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  targets:
    - 'latex'
    - 'html'
    - 'man'
    - 'dirhtml'
  doc-root: []
  branch-root:
    - ''
...
