name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: pymongo
url: http://api.mongodb.com/python/current/
path: pymongo.inv
---
name: phplib
url: https://docs.mongodb.com/php-library/master/
path: phplib.inv
---
name: clouddocs
url: https://docs.atlas.mongodb.com/
path: clouddocs.inv
---
name: compass-docs
url: https://docs.mongodb.com/compass/current/
path: compassdocs.inv
...
