fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  targets:
    - 'latex'
    - 'json'
    - 'singlehtml'
    - 'html'
    - 'man'
    - 'epub'
    - 'dirhtml'
  doc-root: []
  branch-root: null
  links:
    - { 'manual': 'v2.4' }
...