site:
  credentials: "~/.mongodb-jira.yaml"
  projects:
   - 'SERVER'
   - 'TOOLS'
  versions: []
changelog:
  # this data is in the global configuration store in the
  # docs-tools/data directory. Modify it there. This configuration
  # object controls the output of the changelog groupings and
  # components.
  source: changelog.yaml
...