target: push
paths:
  remote: /data/sites/docs
  local: public
  static:
    - 'v2.6/sitemap.xml.gz'
    - '10gen-security-gpg-key.asc'
options: [ 'branched', 'recursive' ]
env: publication
dependency: push-if-up-to-date
---
target: push-with-delete
paths:
  remote: /data/sites/docs
  local: public
  static:
    - 'v2.6/sitemap.xml.gz'
    - '10gen-security-gpg-key.asc'
options: [ 'delete', 'branched', 'recursive' ]
env: publication
dependency: publish
---
target: stage
paths:
  remote: /srv/public/test
  local: public
  static: [ ]
options: [ 'branched', 'recursive' ]
env: staging
dependency: stage-if-up-to-date
---
target: stage-with-delete
paths:
  remote: /srv/public/test
  local: public
  static: [ ]
options: [ 'delete', 'branched', 'recursive' ]
env: staging
dependency: publish
...
