from: '/release-notes/2.8'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8-upgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8-downgrade'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8-compatibility'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8-general-improvements'
to: '/release-notes'
type: 'redirect'
code: 301
outputs:
  - 'before-v2.6'
---
from: '/release-notes/2.8'
to: '/release-notes/2.8'
type: 'redirect'
code: 303
outputs:
  - {'manual': 'v2.8'}
---
from: '/release-notes/2.8-upgrade'
to: '/release-notes/2.8-upgrade'
type: 'redirect'
code: 303
outputs:
  - {'manual': 'v2.8'}
---
from: '/release-notes/2.8-downgrade'
to: '/release-notes/2.8-downgrade'
type: 'redirect'
code: 303
outputs:
  - {'manual': 'v2.8'}
---
from: '/release-notes/2.8-compatibility'
to: '/release-notes/2.8-compatibility'
type: 'redirect'
code: 303
outputs:
  - {'manual': 'v2.8'}
---
from: '/release-notes/2.8-general-improvements'
to: '/release-notes/2.8-general-improvements'
type: 'redirect'
code: 303
outputs:
  - {'manual': 'v2.8'}
...